[book]
authors = ["Björn K. Holmström"]
language = "en"
multilingual = false
src = "src"
title = "Globalize: Natural Steps Toward a Thriving World Government"

[output.html]
additional-css = ["theme/custom.css"]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "your-repo-url"
git-repository-icon = "fa-github"

[output.html.print]
enable = true    # Enable PDF generation
